### ISSUE TITLE
service catalog factory version command fails

### ISSUE THREAD

**Issue by rezamt** [awslabs/aws-service-catalog-factory#155]
Hi Team
I am trying to run all steps from CLI and noticed the servicecatalog-factory version is failing with the following error:
```
cli version: 0.46.0
regional stack version: 0.46.0 for region: ap-southeast-2
Traceback (most recent call last):
  File "/Users/reza/.pyenv/versions/3.8.0/bin/servicecatalog-factory", line 11, in <module>
    load_entry_point('aws-service-catalog-factory==0.46.0', 'console_scripts', 'servicecatalog-factory')()
  File "/Users/reza/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/reza/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/reza/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/reza/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/reza/.pyenv/versions/3.8.0/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/reza/.pyenv/versions/3.8.0/lib/python3.8/site-packages/servicecatalog_factory/cli.py", line 117, in version
    core.version()
  File "/Users/reza/.pyenv/versions/3.8.0/lib/python3.8/site-packages/servicecatalog_factory/core.py", line 913, in version
    click.echo("stack version: {}".format(response.get("Parameter").get("Value"),))
AttributeError: 'str' object has no attribute 'get'
```

Looking inside the config.py - get_stack_version() shows it should return response object not string. 

So either config.py (get_stack_version) or core.py (version() Line #913 ) needs to be change. 

Thanks
Reza
ps: Didn't know how to submit an MR for this.

**Comment by eamonnfaherty** [comment]
Hi @rezamt 

Thanks for raising this issue.

I have now fixed this in version 0.47.1

Sorry for the inconvenience.

Eamonn
