### ISSUE TITLE
Rate limit issue - DescribeChangeSet

### ISSUE THREAD

**Issue by richardmilnerwatts** [awslabs/aws-service-catalog-factory#218]
I had an isolated error with an API rate limit being hit in factory. The error did not occur when I re-ran the pipeline:

```
CreateGenericVersionPipelineTask failed
parameters:
  category: stack
  name: **REDACTED**
  options: <FrozenOrderedDict OrderedDict()>
  source: <FrozenOrderedDict OrderedDict([('Provider', 'S3'), ('Configuration', <FrozenOrderedDict
    OrderedDict([('BucketName', '**REDACTED**-${AWS::AccountId}'), ('S3ObjectKey',
    '**REDACTED**_version1.zip')])>)])>
  stages: <FrozenOrderedDict OrderedDict()>
  version: version1

Traceback (most recent call last):

  File "/root/.pyenv/versions/3.7.10/lib/python3.7/site-packages/luigi/worker.py", line 199, in run
    new_deps = self._run_get_new_deps()

  File "/root/.pyenv/versions/3.7.10/lib/python3.7/site-packages/luigi/worker.py", line 139, in _run_get_new_deps
    task_gen = self.task.run()

  File "/root/.pyenv/versions/3.7.10/lib/python3.7/site-packages/servicecatalog_factory/workflow/generic/create_generic_version_pipeline_task.py", line 63, in run
    StackName=friendly_uid, TemplateBody=template,

  File "/root/.pyenv/versions/3.7.10/lib/python3.7/site-packages/betterboto/cloudformation.py", line 85, in create_or_update
    StackName=stack_name

  File "/root/.pyenv/versions/3.7.10/lib/python3.7/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)

  File "/root/.pyenv/versions/3.7.10/lib/python3.7/site-packages/botocore/client.py", line 635, in _make_api_call
    raise error_class(parsed_response, operation_name)

botocore.exceptions.ClientError: An error occurred (Throttling) when calling the DescribeChangeSet operation (reached max retries: 4): Rate exceeded
```

**Comment by eamonnfaherty** [comment]
change sets with zero changes cannot be executed.  I have added something to delete them in better boto and will include it in the next release: https://github.com/eamonnfaherty/better-boto/releases/tag/0.43.0
