### ISSUE TITLE
Add CodeStarSourceConnection support in schema-portfolios.yaml

### ISSUE THREAD

**Issue by meh485** [awslabs/aws-service-catalog-factory#223]
CodeStarSourceConnection looks to be an approved source provider based on the [service-catalog-tools-workshop](https://service-catalog-tools-workshop.com/every-day-use/100-creating-a-product/305-creating-codestar-pipelines.html), but when running `servicecatalog-factory --info validate .` command, I get the following error:

```
➜  servicecatalog-factory --info validate .
Finished validating: OK
INFO MainThread Validating dir: ./portfolios
INFO MainThread Validating file: reinvent.yaml
Traceback (most recent call last):
  File "~/.pyenv/versions/service-catalog-factory/bin/servicecatalog-factory", line 8, in <module>
    sys.exit(cli())
  File "~/.pyenv/versions/3.9.4/envs/service-catalog-factory/lib/python3.9/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "~/.pyenv/versions/3.9.4/envs/service-catalog-factory/lib/python3.9/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "~/.pyenv/versions/3.9.4/envs/service-catalog-factory/lib/python3.9/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "~/.pyenv/versions/3.9.4/envs/service-catalog-factory/lib/python3.9/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "~/.pyenv/versions/3.9.4/envs/service-catalog-factory/lib/python3.9/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "~/.pyenv/versions/3.9.4/envs/service-catalog-factory/lib/python3.9/site-packages/servicecatalog_factory/cli.py", line 46, in validate
    validate_commands.validate(p)
  File "~/.pyenv/versions/3.9.4/envs/service-catalog-factory/lib/python3.9/site-packages/servicecatalog_factory/commands/validate.py", line 36, in validate
    yamale.validate(schema, data, strict=False)
  File "~/.pyenv/versions/3.9.4/envs/service-catalog-factory/lib/python3.9/site-packages/yamale/yamale.py", line 43, in validate
    raise YamaleError(results)
yamale.yamale_error.YamaleError: Error validating data with schema '~/.pyenv/versions/3.9.4/envs/service-catalog-factory/lib/python3.9/site-packages/servicecatalog_factory/schema/schema-portfolios.yaml'
        Products.0.Versions.0.Source.Provider: 'CodeStarSourceConnection' not in ('CodeCommit',)
        Products.0.Versions.0.Source.Provider: 'CodeStarSourceConnection' not in ('Github',)
        Products.0.Versions.0.Source.Provider: 'CodeStarSourceConnection' not in ('S3',)
        Products.0.Source: Required field missing
        Products.0.Versions.0.Source.Provider: 'CodeStarSourceConnection' not in ('CodeCommit',)
        Products.0.Versions.0.Source.Provider: 'CodeStarSourceConnection' not in ('Github',)
        Products.0.Versions.0.Source.Provider: 'CodeStarSourceConnection' not in ('S3',)
```

I've validated running `servicecatalog-factory --info generate .` locally it successfully creates the pipeline with the codestar connection arn i specify, so I know the platform supports codestarconnection as a source and the schema just needs to be updated to include it as a valid source. Sample of my reinvent.yaml:
```
Schema: factory-2019-04-01
Products:
  - Name: "aws-config-enable-config"
    Owner: "data-governance@example.com"
    Description: "Enables AWS Config"
    Distributor: "cloud-engineering"
    SupportDescription: "Speak to data-governance@example.com about exceptions and speak to cloud-engineering@example.com about implementation issues"
    SupportEmail: "cloud-engineering@example.com"
    SupportUrl: "https://wiki.example.com/cloud-engineering/governance/aws-config-enable-config"
    Tags:
      - Key: "type"
        Value: "governance"
      - Key: "creator"
        Value: "cloud-engineering"
      - Key: "cost-center"
        Value: "cloud-engineering"
    Versions:
      - Name: "v1"
        Description: "v1 of aws-config-enable-config"
        Active: True
        Source:
          Provider: "CodeStarSourceConnection"
          Configuration:
            ConnectionArn: arn:aws:codestar-connections:us-east-1:***********:connection/*********************
            BranchName: "main"
            FullRepositoryId:  <github org name>/aws-config-enable-config

```

**Comment by eamonnfaherty** [comment]
this is released.
