### ISSUE TITLE
Template not found in archive - GovCloud

### ISSUE THREAD

**Issue by puddleglum1904** [awslabs/aws-service-catalog-factory#264]
Factory version: `0.80.0`

I'm receiving the following error when the CodeBuild job `ServiceCatalog-Factory-SharedDeployInGovCloud` runs, as part of a product version pipeline:
```
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.7.13/bin/servicecatalog-factory", line 8, in <module>
    sys.exit(cli())
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/click/core.py", line 717, in main
  rv = self.invoke(ctx)
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/servicecatalog_factory/cli.py", line 521, in create_or_update_provisioning_artifact_from_codepipeline_id
    pipeline_name, pipeline_region, codepipeline_id, region, source_path
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/servicecatalog_factory/cloudformation_servicecatalog_deploy_action.py", line 16, in deploy
    pipeline_name, codepipeline_id, region, source_path
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/site-packages/servicecatalog_factory/cloudformation_servicecatalog_deploy_action.py", line 81, in set_template_url_for_codepipeline_id
    .open(f"{source_path}/product.template-{region}.{template_format}", "r")
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/zipfile.py", line 1503, in open
    zinfo = self.getinfo(name)
  File "/root/.pyenv/versions/3.7.13/lib/python3.7/zipfile.py", line 1431, in getinfo
    'There is no item named %r in the archive' % name)

KeyError: "There is no item named './product.template-us-gov-west-1.yaml' in the archive"
[Container] 2022/06/17 21:49:45 Command did not exit successfully servicecatalog-factory create-or-update-provisioning-artifact-from-codepipeline-id $PIPELINE_NAME $AWS_REGION $CODEPIPELINE_ID us-gov-west-1 exit status 1
[Container] 2022/06/17 21:49:45 Phase complete: BUILD State: FAILED
[Container] 2022/06/17 21:49:45 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: servicecatalog-factory create-or-update-provisioning-artifact-from-codepipeline-id $PIPELINE_NAME $AWS_REGION $CODEPIPELINE_ID us-gov-west-1. Reason: exit status 1
```

I pulled the archive file path directly from the CodeBuild job, downloaded the zip and verified that the file does exist.

Trying to debug this, and found this comment in the source code: 
https://github.com/awslabs/aws-service-catalog-factory/blob/f97030f710e908189e0eb650f0303be73c5e3b04/servicecatalog_factory/cloudformation_servicecatalog_deploy_action.py#L55

Can you please advise how I can correct or get around this error? This is currently blocking all of our pipelines in GovCloud.

**Comment by eamonnfaherty** [comment]
I have been unable to reproduce this so far.  Could you please email me the full output for the deploy step please.

**Comment by eamonnfaherty** [comment]
this has been resolved.
